import type { Metadata } from "next";
import SkeithAgent from "@/components/SkeithAgent";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Type-safe configuration
type LayoutConfig = {
  metadata: Metadata;
  ui: {
    baseStyles: string;
  };
};

// Centralized configuration
const CONFIG: LayoutConfig = {
  metadata: {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: "width=device-width, initial-scale=1",
    themeColor: "#ffffff",
  },
  ui: {
    baseStyles: "antialiased min-h-screen bg-white text-gray-900",
  },
};

// Font initialization (must be explicit literals)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Component composition
type RootLayoutProps = {
  children: React.ReactNode;
  agent?: React.ReactNode;
};

const RootLayoutContainer: React.FC<RootLayoutProps> = ({ 
  children, 
  agent 
}) => (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} ${CONFIG.ui.baseStyles}`}
    >
      <main className="relative">
        {children}
        {agent}
      </main>
    </body>
  </html>
);

// Default export
export const metadata: Metadata = CONFIG.metadata;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootLayoutContainer agent={<SkeithAgent />}>
      {children}
    </RootLayoutContainer>
  );
}